[pytest]
testpaths =
    tests
markers =
    licensee: Licensee-specific tests
norecursedirs =
    .git
    .idea
    .pw_home
    .venv
    Automation-Testing-MCDynect
    .pytest_cache
    results
    test_runs
